
window.GDT=window.GDT||{};if(!GDT._inited){var QBS={bf:[],get:function(){var cb=arguments[4];if(cb){cb({ret:false});}},dom:{get:function(id){return document.getElementById(id);}}};var PMT={get:function(){}};var GDT={bf:[]};(function(){var uin=0;try{uin=QZONE.FP.getQzoneConfig('ownerUin');}catch(e){}
var fileinfo={GDT:{path:'/qzone/biz/ac/comm/',name:'gdtlib',ver:'20140507',getVer:function(){}},COMM:{path:'/qzone/biz/ac/comm/',name:'qbscomm',ver:'20140310',getVer:function(){}}};function getFile(ns){var NS=fileinfo[ns];function _getFileVer(ns){var vs=NS&&NS.ver,nv,v;v=nv=0;if(typeof vs==='string'){return vs;}
try{if(NS.getVer&&typeof NS.getVer==='function'){nv=NS.getVer();}}catch(e){nv=0;}
if(nv>=0&&nv<vs.length){v=nv;}else{}
return vs[v];}
return NS.path+NS.name+'.'+_getFileVer(ns)+'.js';}
var commfile=getFile('COMM');GDT.libfile=getFile('GDT');GDT.filever={defaultrender:'',stat:'20140313',extrender:''};GDT.t='GDT';var cacheUrl={};function _load_js(url,cb,charset,attr,opts){var node,connectId=genHash(url),onload,tmp,doc=document,head;head=doc.head||doc.getElementsByTagName("head")[0]||doc.body;opts=opts||{};fnQueue.add(connectId,cb);if(cacheUrl[connectId]&&cacheUrl[connectId]<0){return;}
if(cacheUrl[connectId]&&cacheUrl[connectId]>0){fnQueue.execOnce(connectId);return;}
cacheUrl[connectId]=-1;node=doc.createElement("script");node.id='_gdt_loader_'+Math.random();node.setAttribute("data-name",connectId);charset=charset||'UTF-8';if(cb){onload=function(){var v=this.readyState;if(typeof v==='undefined'||"loaded"===v||"complete"===v){cacheUrl[connectId]=1;node.onload=node.onreadystatechange=null;node=null;fnQueue.execOnce(connectId);}};node.onreadystatechange=onload;node.onload=onload;}
node.type='text/javascript';node.charset=charset;if(attr){for(var t in attr){if(typeof(tmp=attr[t])=="string"&&t.toLowerCase()!="src"){node.setAttribute(k,tmp);}}}
node.src=url;head.appendChild(node);}
function genHash(str){var hash=5381;str=str||'';for(var i=0,len=str.length;i<len;++i){hash+=(hash<<5)+str.charAt(i).charCodeAt();}
return hash&0x7fffffff;}
var slice=Array.prototype.slice;var loading=false,commloaded,fnQueue;fnQueue={fnlist:{},exec:function(key){var fn,len,i,queue=fnQueue.fnlist[key]||[],args=slice.call(arguments,1);len=queue.length;for(i=0;i<len;i++){fn=queue[i];fn.apply(null,args);}},execOnce:function(key){var queue;fnQueue.exec(key);fnQueue.fnlist[key]=[];},add:function(key,cb){!fnQueue.fnlist[key]&&(fnQueue.fnlist[key]=[]);fnQueue.fnlist[key].push(cb);}};function k(a){a.genHash=genHash;a.fnQueue=fnQueue;a.exec=function(){var fnlist=['get','dealpos','load'];for(var i=fnlist.length-1;i>=0;i--){var fname=fnlist[i],realfname='_'+fname;a[realfname]&&a._exec(fname,a[realfname]);}};a._exec=function(type,fn){var arg;while(arg=a.dequeue(type)){fn.apply(null,arg);}};a.enqueue=function(type,value){a.bf[type]=a.bf[type]||[];a.bf[type].push(value);};a.dequeue=function(type){var n;if(a.bf[type]){n=a.bf[type].shift();}
return n;};a.onPreGet=function(){};a.importJs=function(){var args=slice.call(arguments);setTimeout(function(){_load_js.apply(null,args);},0);};a.fp=(function(){var _fp=window,found=0;var _isfp=function(){return!!(_fp.QZONE&&_fp.QZONE.FrontPage&&_fp.QZFL&&_fp.g_iUin);};try{if(_isfp()){found=5;}else{do{_fp=_fp.parent;if(_isfp()){found=5;break;}}while(_fp!=top);}}catch(ex){found=0;}
if(found<5){return false;}
return _fp;})();var fk=a.fp;a.imgcacheDomain=(!!fk&&fk.imgcacheDomain)?fk.imgcacheDomain:'imgcache.qq.com';a.siDomain=(!!fk&&fk.siDomain)?fk.siDomain:"qzonestyle.gtimg.cn";var d=a.siDomain;a.lib={_file:'http://'+d+a.libfile,_loading:false,load:function(){if(!a.lib._loading){a.lib._loading=true;_load_js(a.lib._file,function(){if(a._get){a.exec();}},'utf-8',{'async':true});}}};var comurl='http://'+d+commfile;if(!fk&&!loading){loading=true;_load_js(comurl,function(){if(typeof __qbs_load_comm!='undefined'){commloaded=true;fnQueue.execOnce('comm');}});}
var loadlib=function(){if(!fk&&!commloaded){fnQueue.add('comm',function(){a.lib.load();});}else{a.lib.load();}};if(a.t=='GDT'){loadlib();}
a.get=function(){var args=slice.call(arguments,0);a.enqueue('get',args);if(a._get){a.exec();}else{loadlib();}};a.dealpos=function(){var args=slice.call(arguments,0);a.enqueue('dealpos',args);if(a._dealpos){a.exec();}};a.load=function(){var args=slice.call(arguments,0);a.enqueue('load',args);if(a._load){a.exec();}else{loadlib();}};}
k(GDT);})();GDT._inited=true;}